// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/mail/mail.proto

package mail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextMailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMailReq) Reset() {
	*x = TextMailReq{}
	mi := &file_proto_mail_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMailReq) ProtoMessage() {}

func (x *TextMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMailReq.ProtoReflect.Descriptor instead.
func (*TextMailReq) Descriptor() ([]byte, []int) {
	return file_proto_mail_mail_proto_rawDescGZIP(), []int{0}
}

func (x *TextMailReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TextMailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TextMailReq) GetContent() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_proto_mail_mail_proto protoreflect.FileDescriptor

const file_proto_mail_mail_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mail/mail.proto\x12\amail.v1\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\vTextMailReq\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent2K\n" +
	"\vMailService\x12<\n" +
	"\fSendTextMail\x12\x14.mail.v1.TextMailReq\x1a\x16.google.protobuf.EmptyB;Z9github.com/qq754174349/ht/notification/pkg/grpc/mail;mailb\x06proto3"

var (
	file_proto_mail_mail_proto_rawDescOnce sync.Once
	file_proto_mail_mail_proto_rawDescData []byte
)

func file_proto_mail_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_mail_proto_rawDesc), len(file_proto_mail_mail_proto_rawDesc)))
	})
	return file_proto_mail_mail_proto_rawDescData
}

var file_proto_mail_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_mail_mail_proto_goTypes = []any{
	(*TextMailReq)(nil),   // 0: mail.v1.TextMailReq
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_proto_mail_mail_proto_depIdxs = []int32{
	0, // 0: mail.v1.MailService.SendTextMail:input_type -> mail.v1.TextMailReq
	1, // 1: mail.v1.MailService.SendTextMail:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mail_mail_proto_init() }
func file_proto_mail_mail_proto_init() {
	if File_proto_mail_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_mail_proto_rawDesc), len(file_proto_mail_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mail_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_mail_proto = out.File
	file_proto_mail_mail_proto_goTypes = nil
	file_proto_mail_mail_proto_depIdxs = nil
}
