web:
  port: "9000"
log:
  level: "debug"
  output_paths: "logs/"

orm:
  mysql:
    user:
      host: "127.0.0.1"
      port: "3306"
      user: "root"
      password: "123456"
      database: "ht"
redis:
  cache:
    addr: "127.0.0.1:6379"
    user: ""
    password: ""
    db: 0