web:
  port: "9001"
log:
  level: "debug"
  output_paths: "logs/"

mysql:
  user:
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    password: "123456"
    database: "ht"
redis:
  cache:
    addr: "127.0.0.1:6379"
    user: ""
    password: ""
    db: 0
mail:
  host: "smtp.163.com"
  port: "465"
  username: "everyday_sentence@163.com"
  password: "XWTh2AtMUR59CbcB"